title: git-java1
description: this is a repsitory i created for php php
template:
  repo: git-java1-template
  name: git-java1
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
